#ifndef HOST_LINK_PROTOCOL_H
#define HOST_LINK_PROTOCOL_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define HOST_LINK_PROTOCOL_VERSION      0x01u
#define HOST_LINK_SOF1                  0xAAu
#define HOST_LINK_SOF2                  0x55u
#define HOST_LINK_EOF                   0x33u
#define HOST_LINK_MAX_PAYLOAD_SIZE      512u
#define HOST_LINK_MAX_FRAME_SIZE        (HOST_LINK_MAX_PAYLOAD_SIZE + 11u)

typedef enum
{
    HOST_LINK_TYPE_PING = 0x01,
    HOST_LINK_TYPE_PONG = 0x02,
    HOST_LINK_TYPE_GET_DEVICE_INFO = 0x03,
    HOST_LINK_TYPE_DEVICE_INFO = 0x04,
    HOST_LINK_TYPE_ACK = 0x05,
    HOST_LINK_TYPE_NACK = 0x06,

    HOST_LINK_TYPE_SET_STREAM_CONFIG = 0x10,
    HOST_LINK_TYPE_GET_STREAM_CONFIG = 0x11,
    HOST_LINK_TYPE_STREAM_CONFIG = 0x12,
    HOST_LINK_TYPE_TELEMETRY_SAMPLE = 0x13,

    HOST_LINK_TYPE_GET_PARAMETER_TABLE = 0x20,
    HOST_LINK_TYPE_PARAMETER_TABLE = 0x21,
    HOST_LINK_TYPE_READ_PARAMETER = 0x22,
    HOST_LINK_TYPE_WRITE_PARAMETER = 0x23,
    HOST_LINK_TYPE_PARAMETER_VALUE = 0x24,
    HOST_LINK_TYPE_SAVE_PARAMETERS = 0x25,
    HOST_LINK_TYPE_LOAD_PARAMETERS = 0x26,

    HOST_LINK_TYPE_EVENT = 0x40,
    HOST_LINK_TYPE_FAULT = 0x41,
    HOST_LINK_TYPE_LOG_TEXT = 0x42,
    HOST_LINK_TYPE_STATE_SNAPSHOT = 0x43,
} HostLinkMessageType_t;

typedef enum
{
    HOST_LINK_FLAG_NONE = 0x00,
    HOST_LINK_FLAG_ACK_REQUIRED = 0x01,
    HOST_LINK_FLAG_STREAM = 0x02,
    HOST_LINK_FLAG_ERROR = 0x80,
} HostLinkFlags_t;

typedef enum
{
    HOST_LINK_MODE_BOOT = 0x00,
    HOST_LINK_MODE_IDLE = 0x01,
    HOST_LINK_MODE_ARMED = 0x02,
    HOST_LINK_MODE_BALANCING = 0x03,
    HOST_LINK_MODE_FAULT = 0x04,
    HOST_LINK_MODE_CALIBRATION = 0x05,
    HOST_LINK_MODE_TEST = 0x06,
} HostLinkMode_t;

typedef enum
{
    HOST_LINK_ERR_NONE = 0x00,
    HOST_LINK_ERR_BAD_LENGTH = 0x01,
    HOST_LINK_ERR_BAD_CRC = 0x02,
    HOST_LINK_ERR_BAD_VERSION = 0x03,
    HOST_LINK_ERR_UNKNOWN_TYPE = 0x04,
    HOST_LINK_ERR_PARAM_NOT_FOUND = 0x05,
    HOST_LINK_ERR_PARAM_READ_ONLY = 0x06,
    HOST_LINK_ERR_PARAM_OUT_OF_RANGE = 0x07,
    HOST_LINK_ERR_STORAGE = 0x08,
    HOST_LINK_ERR_BUSY = 0x09,
} HostLinkError_t;

typedef enum
{
    HOST_LINK_PARAM_TYPE_BOOL = 0x01,
    HOST_LINK_PARAM_TYPE_U8 = 0x02,
    HOST_LINK_PARAM_TYPE_I32 = 0x03,
    HOST_LINK_PARAM_TYPE_F32 = 0x04,
} HostLinkParamType_t;

typedef enum
{
    HOST_LINK_STREAM_CONTROL_FAST = 0x01,
    HOST_LINK_STREAM_SENSORS = 0x02,
    HOST_LINK_STREAM_ACTUATORS_POWER = 0x03,
    HOST_LINK_STREAM_RUNTIME_HEALTH = 0x04,
    HOST_LINK_STREAM_ENCODERS = 0x05,
    HOST_LINK_STREAM_FAULT_FOCUS = 0x06,
} HostLinkStreamId_t;

typedef enum
{
    HOST_LINK_EVENT_BOOT_COMPLETE = 0x0101,
    HOST_LINK_EVENT_MODE_CHANGED = 0x0102,
    HOST_LINK_EVENT_PARAMETER_CHANGED = 0x0103,
    HOST_LINK_EVENT_PARAMETERS_SAVED = 0x0104,
    HOST_LINK_EVENT_CAPTURE_READY = 0x0105,
    HOST_LINK_EVENT_STREAM_OVERRUN = 0x0106,
} HostLinkEventCode_t;

#define HOST_LINK_PARAM_FLAG_READ_ONLY   0x01u
#define HOST_LINK_PARAM_FLAG_PERSISTENT  0x02u
#define HOST_LINK_PARAM_FLAG_EXPERT      0x04u

#ifdef __cplusplus
}
#endif

#endif /* HOST_LINK_PROTOCOL_H */
